name: Update Quote

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 06:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch a new quote
        run: curl -sk https://api.quotable.io/random > quote.json

      - name: Update README with new quote
        run: |
          QUOTE=$(jq -r '.content' quote.json)
          AUTHOR=$(jq -r '.author' quote.json)

          # Escape special characters for sed
          QUOTE_ESCAPED=$(printf '%s' "$QUOTE" | sed 's/[&/\]/\\&/g')
          AUTHOR_ESCAPED=$(printf '%s' "$AUTHOR" | sed 's/[&/\]/\\&/g')

          # Update README.md
          sed -i "/<!--START_QUOTE-->/,/<!--END_QUOTE-->/c\\<!--START_QUOTE-->\n> $QUOTE_ESCAPED\n— $AUTHOR_ESCAPED\n<!--END_QUOTE-->" README.md

          # Append to quotes.md to keep history
          echo -e "### $(date '+%Y-%m-%d')\n> $QUOTE_ESCAPED\n— $AUTHOR_ESCAPED\n" >> quotes.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add quotes.md || true
          git commit -m "Update quote: $(date)" || echo "No changes to commit"
          git push    
