name: Update Daily Quote

on:
  schedule:
    - cron: "0 6 * * *"   # Runs daily at 06:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Random Quote
        run: |
          curl -s https://api.quotable.io/random > quote.json
          QUOTE=$(jq -r '.content' quote.json)
          AUTHOR=$(jq -r '.author' quote.json)
          echo "# Daily Quote" > quotes.md
          echo "" >> quotes.md
          echo "> $QUOTE" >> quotes.md
          echo "" >> quotes.md
          echo "— $AUTHOR" >> quotes.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add quotes.md
          git commit -m "Update quote: $(date)" || echo "No changes to commit"
          git push
