name: Update Daily Quote

on:
  schedule:
    - cron: "0 6 * * *"   # Runs daily at 06:00 UTC
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write    # allow pushing changes

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Get Random Quote
        run: |
          curl -sk https://api.quotable.io/random > quote.json
          QUOTE=$(jq -r '.content' quote.json)
          AUTHOR=$(jq -r '.author' quote.json)

          # Update quotes.md (keeps latest only)
          echo "# Daily Quote" > quotes.md
          echo "" >> quotes.md
          echo "> $QUOTE" >> quotes.md
          echo "" >> quotes.md
          echo "— $AUTHOR" >> quotes.md

          # Update README.md section
          sed -i '/<!--START_QUOTE-->/,<!--END_QUOTE-->/c\<!--START_QUOTE-->\n> '"$QUOTE"'\n\n— '"$AUTHOR"'\n<!--END_QUOTE-->' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add quotes.md README.md || true
          git commit -m "Update daily quote: $(date)" || echo "No changes to commit"
          git push
