name: Update Quote

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 06:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch a new quote
        run: curl -s https://api.quotable.io/random > quote.json

      - name: Update README with new quote
        run: |
          QUOTE=$(jq -r '.content' quote.json)
          AUTHOR=$(jq -r '.author' quote.json)

          # Escape special characters for sed
          QUOTE_ESCAPED=$(printf '%s' "$QUOTE" | sed 's/[&/\]/\\&/g')
          AUTHOR_ESCAPED=$(printf '%s' "$AUTHOR" | sed 's/[&/\]/\\&/g')

          sed -i "/<!--START_QUOTE-->/,/<!--END_QUOTE-->/c\\<!--START_QUOTE-->\n> $QUOTE_ESCAPED\n— $AUTHOR_ESCAPED\n<!--END_QUOTE-->" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update daily quote" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
